[build]
  command = "CI=false npm run build"
  publish = "out"
  environment = { NEXT_PUBLIC_REACT_APP_URL = 'https://hackillinois.org' }

[functions]
  directory = "functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"